name: 'lightning'

services:
  bitcoind:
    image: lightninglabs/bitcoin-core
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - '8332:8332'
    healthcheck:
      test: curl --fail http://localhost:8332/rest/chaininfo.json || exit 1
      start_period: 120s
      interval: 30s
      timeout: 60s
      retries: 10
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    command: >
      bitcoind -conf=/home/bitcoin/.bitcoin/bitcoin.conf

  lnd:
    image: lightninglabs/lnd:v0.19.3-beta
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/lightning:/root/.lnd
    ports:
      - '8080:8080'
      - '9735:9735'
    healthcheck:
      test: 'curl --fail --insecure --header "Grpc-Metadata-macaroon: $MACAROON" https://localhost:8080/v1/getinfo || exit 1'
      start_period: 120s
      interval: 30s
      timeout: 60s
      retries: 10
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      bitcoind:
        condition: service_healthy
    command: >
      lnd --configfile=/root/.lnd/lnd.conf --bitcoin.mainnet

  tapd:
    image: polarlightning/tapd:0.3.3-alpha
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/lightning:/home/tap/.lnd
      - ./volumes/taproot:/home/tap/.tapd
      - ./volumes/taproot/tapd.conf:/home/tap/tapd.conf
    ports:
      - '8089:8089'
      - '6060:6060'
    depends_on:
      lnd:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    command: >
      tapd --configfile=/home/tap/tapd.conf

  lnbits:
    image: lnbits/lnbits:0.12.8
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/lightning:/app/.lnd
      - ./volumes/lnbits/data:/app/data
      - ./volumes/lnbits/.env:/app/.env
    ports:
      - '5000:5000'
    healthcheck:
      test: curl --fail --insecure https://localhost:5000/api/v1/health || exit 1
      start_period: 60s
      interval: 60s
      timeout: 30s
      retries: 10
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      lnd:
        condition: service_healthy
    command: >
      poetry run lnbits --ssl-keyfile /app/.lnd/tls.key --ssl-certfile /app/.lnd/tls.cert

  lnbitsapi:
    image: dfxswiss/lnbitsapi:main
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/lnbitsapi/data:/home/node/data
      - ./volumes/lnbits/data:/home/node/data/sqlite3
      - ./volumes/lnbitsapi/.env:/home/node/.env
    ports:
      - '5001:5001'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      lnbits:
        condition: service_healthy

  thunderhub:
    image: apotdevin/thunderhub:v0.13.31
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/lightning:/app/.lnd
      - ./volumes/thunderhub/.env:/app/.env
      - ./volumes/thunderhub/accounts.yml:/app/accounts.yml
    ports:
      - '3000:3000'
    depends_on:
      lnd:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'

networks:
  shared:
    external: true
    name: lightning-network
